### ISSUE TITLE
ImportError: cannot import name HTTPResponse

### ISSUE THREAD

**Issue by jacekjaros** [epitron/mitm-adblock#2]
OS Debian 9.0
mitmproxy 0.18.2-6
Python 2.7.13

```
# ./go --help
* Starting proxy server on port 8118...
Loading script: adblock.py
Script error: Traceback (most recent call last):
  File "adblock.py", line 10, in <module>
    from mitmproxy.protocol.http import HTTPResponse
ImportError: cannot import name HTTPResponse
```

**Comment by epitron** [comment]
Hmm... it looks like `mitmproxy` reorganized their library. Try changing that line to:

`from mitmproxy.http import HTTPResponse`

**Comment by zqhong** [comment]
@epitron 

Why not freeze python requirement?
Using ` pip freeze > requirements.txt`, add upload requirements.txt to GitHub. If someone wants to install mitm-adblock, he just run `pip install -r requirements.txt`.

**Comment by epitron** [comment]
That's a good idea, @zqhong; I'll add one of those.

**Comment by emptak123** [comment]
Script error: Traceback (most recent call last):
  File "adblock.py", line 10, in <module>
    from mitmproxy.http import HTTPResponse
ImportError: No module named http

im geting the same error but the line 

from mitmproxy.http import HTTPResponse 

is ok 

any hints ?

**Comment by szborows** [comment]
please see https://github.com/epitron/mitm-adblock/pull/4 where `requirements.txt` is added and whole tool is fixed to work with most recent version of mitmproxy (5.1.1)

obviously you can test it on my fork

**Comment by epitron** [comment]
Nice! Thanks, @szborows!
