### ISSUE TITLE
updating Adblock.py for MITMProxy 4.0.4 and Python 3.7

### ISSUE THREAD

**Issue by onaniee** [epitron/mitm-adblock#3]
Firstly, thank you very much epitron and davizucon for this project. It's increasingly relevant these days.

Secondly, I'm trying to run Adblock.py with MITMProxy 4.0.4 under python 3.7 and have been encountering issues. As a complete Python noob, I've done a couple of very minor modifications to address error messages as they come up:

- changed "import mitmproxy.protocol.http" to "mitmproxy.http" to fix HTTPResponse import error.
- deleted "from netlib.odict import ODictCaseless" to fix import error message
- changed "def request(context, flow):" to "def request(flow):" to fix "TypeError: request() missing 1 required positional argument: 'flow'"

I'm still left with the error message:
```
  File "adblock.py", line 79, in request
    if rules.should_block(req.url, options):
NameError: name 'rules' is not defined
```

I'm not sure how to proceed from there, after everything I've tried to somehow define the 'rules' object. Also not sure if the minor changes I've detailed above have broken anything.

Thanks again.
Cheers.

**Comment by epitron** [comment]
Hi @onaniee, 

Glad you're interested in this tool!

I haven't used it in quite some time, and code-rot seems to have set in. I get one of the pip dependencies (`re2`) to build against Python 3 anymore (lots of deprecations).

Did you give up?

**Comment by epitron** [comment]
I just fixed all the issues. `mitmproxy` simplified how their scripts work, and moved some modules around. Try it now!

**Comment by onaniee** [comment]
Hi! Thanks for the prompt reply. I'll give it a go, and I'm sure to learn something from your code.

Thanks again for this awesome project.

**Comment by epitron** [comment]
You're welcome! And thanks for the interest.
